.TH "UTIMER" "1" "June 1, 2009" "" "uTimer"
.SH "NAME"
\fButimer\fP \- command\-line "timer" tool which features a timer, a countdown and a stopwatch.

.SH "SYNOPSIS"
.B utimer
.RI [\-\-timer=TIMELENGTH\ |\ \-t\ TIMELENGTH]
.RI [\-\-countdown=TIMELENGTH\ |\ \-c\ TIMELENGTH]
.RI [\-\-quiet\ |\ \-q]
.RI [\-\-verbose\ |\ \-v]
.RI [\-\-quit\-with\-success]

.B utimer
.RI [\-\-limits\ |\ \-L]

.B utimer
.RI [\-\-version]
.SH "DESCRIPTION"
.B utimer
or 
.B µTimer
(pronounced "micro\-timer") is a multifunction timer (command\-line only). It features a timer, a countdown, and a stopwatch.

The
.B timer
counts the elapsed time, increasing to reach the given time length and then stops. Given a time length, the timer will "sleep", wait or pause till the time length has passed, then exits. Compared to the linux
.B sleep
function, µTimer actually shows the current elapsed time which can be useful for long time lengths.

The
.B countdown,
compared to the timer, has the only difference that the starting point is the given time length and it will decrease to reach 0. When it reaches 0 (when the time length has passed), the program exits. It can be very useful for creating scripts.

The
.B stopwatch
is like a real stopwatch where you can measure time of multiple events, or use it for (board) games, or anything else. It starts counting time when the program is started, and it can be stopped (using the 'Q' key) or otherwise you can just hit the ENTER key when you have to take multiple measures without stopping the counting.

.LP 
.SH "OPTIONS"
.B
.IP --help\ |\ \-?
Print the command line options.
.B
.IP --timer=TIMELENGTH\ |\ \-t\ TIMELENGTH
Shows a timer that runs until TIMELENGTH has passed. TIMELENGTH is a pattern that should look like: 2d15h39m58s120ms. See the 
.B Timer
section in
.B USAGE
to read more about how to use the timer.
.B
.IP --countdown=TIMELENGTH\ |\ \-c\ TIMELENGTH
Shows a countdown that runs until TIMELENGTH has passed (until it reaches zero). TIMELENGTH is a pattern that should look like: 2d15h39m58s120ms. See the 
.B Countdown
section in
.B USAGE
to read more about how to use the countdown.
.B
.IP --stopwatch\ |\ \-s
Starts the stopwatch that runs until it is stopped using the 'Q' key or by other means (Ctrl+C, system signals, ...). See the 
.B Stopwatch
section in
.B USAGE
to read more about how to use the stopwatch.
.B
.IP --verbose\ |\ \-v
Print more information during the program's process. (note that if used with -q, this option is ignored)
.B
.IP --quiet\ |\ \-q
Quiet or silent output (almost no output) (note that if used with -v, -v is ignored).
.B
.IP --debug\ |\ \-D
Show debug information in output (should ONLY be used for bug reporting, for developers or for testing purposes).
.B
.IP --limits\ |\ \-L
Display the limits of
.B µTimer
for your machine (maximum values, longest timer, ...). It may be not be perfectly accurate. Use this option only to have an idea of what it can do.
.B
.IP --quit-with-success
When you quit the program using the 'q' key, it will exit with a success exit status code, instead of an error one normally. (Note that 'ctrl+c' isn't affected by this option)
.SH "USAGE"
.B
.IP Timer:


.B utimer --timer=TIMELENGTH
or
.B utimer -t TIMELENGTH

When using the timer, µTimer will show the current elapsed time and then will exit when TIMELENGTH is reached (read: when that TIMELENGTH has passed).
The TIMELENGTH is composed of pairs of: a value + a suffix (for example "39d" for 39 days). It can be in any order, and there is no space between each pair. Each value 
.B must be a positive integer
and can be null (0). The suffix is case
.B sensitive
(see below for the suffixes list). 

Here's a few valid examples of TIMELENGTH:
55s,
2m450ms,
0s,
0d32h,
9m7h30s80ms6d,
1d0h0m50s.

Supported suffixes are:
.B d
for days,
.B h
for hours,
.B m
for minutes,
.B s
for seconds,
.B ms
for milliseconds.

.B
.IP Countdown:

.B utimer --countdown=TIMELENGTH
or
.B utimer -c TIMELENGTH

When using the countdown, µTimer will show the current remaining time before exiting. After TIMELENGTH has passed -or when the remaining time reaches zero (0)- µTimer exits.
See the Timer usage to know how to write a valid TIMELENGTH.
.B
.IP Stopwatch:

.B utimer --stopwatch
or
.B utimer -s

When using the stopwatch, it counts until it is stopped using the 'Q' key or Ctrl+C or certain system signals (SIGKILL for example).
You can use the ENTER key to take measures (like a snapshot) of the elapsed time.


.SH SHORTCUT KEYS

.B
.IP 'Q':


You can stop/quit the timer whenever by using the 'Q' key, note that the program will exit with a error exit status code (1) (you can bypass this behaviour by using the
.B --quit-with-success
option, see the
.B EXIT_STATUS
section above).

.B
.IP SPACEBAR:

You can pause the timer anytime using the spacebar key. To resume, just hit the spacebar again.

.B
.IP ENTER:

With the stopwatch, you can use the ENTER key to take measures (like a snapshot) of the elapsed time.

.SH EXIT STATUS
After the timer or the countdown are done, the program exits with a success exit status code (0). But when you quit during the timer/countdown is counting using 'q', it exits with an error exit status code (1). You can change this behaviour using the 
.B --quit-with-success
option. (Note that 'ctrl+c' isn't affected by this option)

.SH "EXAMPLE"
.IP Timer:


.B utimer \-t 20s900ms
runs the timer for 20 seconds and 900 milliseconds.
.IP
.B utimer \--timer=1d
runs the timer for a whole day.

.IP Countdown:

.B utimer \-c 1m48s500ms
runs the countdown for 1 minute, 48 seconds and 500 milliseconds.
.IP
.B utimer \--countdown=2d5m
runs the countdown for 2 days plus 5 minutes.

.IP Stopwatch:

.B utimer \-s
starts the stopwatch.


.SH "ACCURACY"
The timer can be accurate enough for most common uses, and we cannot give any warranty on its accuracy. This is due to the time needed to start and to exit the program. On our test machines, it's as low as 5 milliseconds.
.SH "BUGS"
If you find any bug using µTimer, please report it to:

.B https://bugs.launchpad.net/utimer

.B or
send it to:

.B bugs@utimer.codealpha.net
.SH "AUTHOR"
Arnaud "Weboide" Soyez <weboide@codealpha.net>
